settings:
  system:
    token: 'NDk1MDU2MjExMzM5NzcxOTE3.Do8gsw.jjgr4p7Z56w9O_RLTznBbze3u7M'
    commandprefix: '!cmd '
    requireemail: 'Yes'
    consoleloglevel: 'DEBUG'
    fileloglevel: "DEBUG"
  integrations:
    wordpress: 'No'
    connection: 'Oauth2'
    webaddress: 'http://instance.id'
  discord:
    guild: '468705323088085012'
    botusers:
      - '498336546987048970'
      - '498336546987048970'
    roles:
      Verified: '468710520002969600'
      SCT: '495402309912756242'
      UFPS1: '495402356612268035'
      TPC: '503852507882323989'
      FPC: '503853845668036617'
  assets:
    datecompare: 'Yes'
    comparedate: '2018-08-31'
    assetoriginal: 'TPC1'
    assetteplacement: 'TPC'
    apiKey:
      SCT: '3LuhEVAn0fKx7giKOH8jda7aft8'
      UCC: 'HRa4vZFa8jXisIJSj9vw9TrOyRk'
      TPC: 'HRa4vZFa8jXisIJSj9vw9TrOyRk'
      UTPS: 'HRa4vZFa8jXisIJSj9vw9TrOyRk'
      UTPM: 'HRa4vZFa8jXisIJSj9vw9TrOyRk'
      TPC1: 'HRa4vZFa8jXisIJSj9vw9TrOyRk'
      FPC: 'HRa4vZFa8jXisIJSj9vw9TrOyRk'
      UFPS: 'HRa4vZFa8jXisIJSj9vw9TrOyRk'
      UFPM: 'HRa4vZFa8jXisIJSj9vw9TrOyRk'
      UFPS1: '5AS4zMOcLj3aaF2T1eEVioQsT04'
      BD: 'HRa4vZFa8jXisIJSj9vw9TrOyRk'
    package:
      SCT: 'SCT - Scriptable Text'
      UCC: 'Ultimate Character Controller'
      TPC: 'Third Person Controller'
      TPS: 'UTPS: Ultimate Third Person Shooter'
      UTPM: 'UTPM: Ultimate Third Person Melee'
      TPC1: 'Third Person Controller'
      FPC: 'First Person Controller'
      UFPS: 'UFPS: Ultimate First Person Shooter'
      UFPM: 'UFPM: Ultimate First Person Melee'
      UFPS1: 'UFPS : Ultimate FPS'
      BD: 'Behavior Designer - Behavior Trees for Everyone'