settings:
  assets:
    apikey:
      BD: HRa4vZFa8jXisIJSj9vw9TrOyRk
      FPC: HRa4vZFa8jXisIJSj9vw9TrOyRk
      SCT: 3LuhEVAn0fKx7giKOH8jda7aft8
      TPC: HRa4vZFa8jXisIJSj9vw9TrOyRk
      TPC1: HRa4vZFa8jXisIJSj9vw9TrOyRk
      UCC: HRa4vZFa8jXisIJSj9vw9TrOyRk
      UFPM: HRa4vZFa8jXisIJSj9vw9TrOyRk
      UFPS: HRa4vZFa8jXisIJSj9vw9TrOyRk
      UFPS1: 5AS4zMOcLj3aaF2T1eEVioQsT04
      UTPM: HRa4vZFa8jXisIJSj9vw9TrOyRk
      UTPS: HRa4vZFa8jXisIJSj9vw9TrOyRk
    assetoriginal: TPC1
    assetreplacement: TPC
    comparedate: "2018-08-31"
    datecompare: "No"
    package:
      BD: Behavior Designer - Behavior Trees for Everyone
      FPC: First Person Controller
      SCT: SCT - Scriptable Text
      TPC: Third Person Controller
      TPC1: Third Person Controller
      TPS: 'UTPS: Ultimate Third Person Shooter'
      UCC: Ultimate Character Controller
      UFPM: 'UFPM: Ultimate First Person Melee'
      UFPS: 'UFPS: Ultimate First Person Shooter'
      UFPS1: 'UFPS : Ultimate FPS'
      UTPM: 'UTPM: Ultimate Third Person Melee'
  discord:
    botusers:
    - "498336546987048970"
    - "498336546987048970"
    guild: "468705323088085012"
    roles:
      FPC: "503853845668036617"
      SCT: "495402309912756242"
      TPC: "503852507882323989"
      UFPS1: "495402356612268035"
      Verified: "468710520002969600"
  integrations:
    connection: Oauth2
    webaddress: http://instance.id
    wordpress: "No"
  system:
    commandprefix: '!cmd '
    consoleloglevel: INFO
    fileloglevel: INFO
    requireemail: "Yes"
    token: NDk1MDU2MjExMzM5NzcxOTE3.Do8gsw.jjgr4p7Z56w9O_RLTznBbze3u7M
